### ISSUE TITLE
dog_descriptions are unparsed .csv

### ISSUE THREAD

**Issue by robertwwalker** [thebioengineer/tidytuesdayR#37] opened 2019-12-18 04:49 UTC
The packaged version of this dataset [dog_descriptions] reads, at least for me, as 220139 observations of 1 variable with rownames listed and separated by commas. It is the unparsed .csv. I suspect this will vex somewhat inexperienced users trying this workflow; directly reading the .csv from github solves it.

**Comment by thebioengineer** [comment] 2019-12-18 06:13
Thanks for @robertwwalker - The issue is the function I have identifying the parser to use isn't handling the multi-line entries for the descriptions. I'll see what I can do about that!

**Comment by thebioengineer** [comment] 2019-12-19 05:12
@robertwwalker Try the latest install now. it should be working now!

**Comment by robertwwalker** [comment] 2019-12-20 16:55
Weirdly, that seems to have corrupted the database

![image](https://user-images.githubusercontent.com/22829624/71270461-7bae0700-2306-11ea-9933-23567f48c928.png)

**Comment by thebioengineer** [comment] 2019-12-20 17:00
That is strange! It passed all my tests and I tested installs on a few computers. 

Try closing out all your R sessions and reinstalling. That is typically when I get those errors - it is due to another R session having loaded the package.

**Comment by robertwwalker** [comment] 2019-12-20 17:07
It was some combination of that and/or vctrs across two environments.  Both now work like a charm.  Thanks much for this; it is very cool to do this to assist people in picking up the tidytuesday!

**Closed** 2019-12-20 17:14 UTC
