### ISSUE TITLE
`tt_load()`  invalid multibyte string error

### ISSUE THREAD

**Issue by statkclee** [thebioengineer/tidytuesdayR#64] opened 2020-07-22 04:56 UTC
I could not figure out " invalid multibyte string" error.

``` r

library(tidytuesdayR)

fines_df <- tt_load("2020-04-21")
#> --- Compiling #TidyTuesday Information for 2020-04-21 ----
#> --- There are 2 files available ---
#> --- Starting Download ---
#> 
#>  Downloading file 1 of 2: `gdpr_text.tsv`
#> Error in nchar(x): invalid multibyte string, element 3
fines_df <- tt_load("2020-04-21", local = locale(encoding = "utf-8"))
#> --- Compiling #TidyTuesday Information for 2020-04-21 ----
#> --- There are 2 files available ---
#> --- Starting Download ---
#> 
#>  Downloading file 1 of 2: `gdpr_text.tsv`
#> Error in nchar(x): invalid multibyte string, element 3
fines_df <- tt_load("2020-04-21", local = locale(encoding = "latin1"))
#> --- Compiling #TidyTuesday Information for 2020-04-21 ----
#> --- There are 2 files available ---
#> --- Starting Download ---
#> 
#>  Downloading file 1 of 2: `gdpr_text.tsv`
#> Error in nchar(x): invalid multibyte string, element 3
sessionInfo()
#> R version 4.0.2 (2020-06-22)
#> Platform: x86_64-apple-darwin17.0 (64-bit)
#> Running under: macOS Catalina 10.15.5
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] tidytuesdayR_1.0.1
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.5       rstudioapi_0.11  xml2_1.3.2       knitr_1.29      
#>  [5] magrittr_1.5     usethis_1.6.1    hms_0.5.3        rvest_0.3.5     
#>  [9] R6_2.4.1         rlang_0.4.7      stringr_1.4.0    httr_1.4.2      
#> [13] highr_0.8        tools_4.0.2      xfun_0.15        selectr_0.4-2   
#> [17] htmltools_0.5.0  ellipsis_0.3.1   readxl_1.3.1     yaml_2.2.1      
#> [21] digest_0.6.25    lifecycle_0.2.0  tibble_3.0.3     crayon_1.3.4    
#> [25] purrr_0.3.4      readr_1.3.1      fs_1.4.2         vctrs_0.3.2     
#> [29] curl_4.3         glue_1.4.1       evaluate_0.14    rmarkdown_2.3   
#> [33] stringi_1.4.6    cellranger_1.1.0 pillar_1.4.6     compiler_4.0.2  
#> [37] generics_0.0.2   jsonlite_1.7.0   lubridate_1.7.9  pkgconfig_2.0.3
```

<sup>Created on 2020-07-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thebioengineer** [comment] 2020-07-22 05:20
That is very strange - the encoding shouldn't matter in this release. Do you get the same error with `gdpr_text <- readr::read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-21/gdpr_text.tsv')
` ?

**Comment by thebioengineer** [comment] 2020-07-22 06:26
if that does not work, could you try the dev version of the package with your same code?

 `remotes::install_github("thebioengineer/tidytuesdayR@dev")`

**Comment by statkclee** [comment] 2020-07-22 23:55
This first one is working as below.

``` r
gdpr_text <- readr::read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-21/gdpr_text.tsv')
#> Parsed with column specification:
#> cols(
#>   chapter = col_double(),
#>   chapter_title = col_character(),
#>   article = col_double(),
#>   article_title = col_character(),
#>   sub_article = col_double(),
#>   gdpr_text = col_character(),
#>   href = col_character()
#> )
```

<sup>Created on 2020-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by statkclee** [comment] 2020-07-22 23:56
But the second one still has the same problem.

``` r
remotes::install_github("thebioengineer/tidytuesdayR@dev", force = TRUE)
#> Using github PAT from envvar GITHUB_PAT
#> Downloading GitHub repo thebioengineer/tidytuesdayR@dev
#> 
#>      checking for file ‘/private/var/folders/cg/0x9z12457xv1910wjyj19b1w0000gp/T/RtmpqOyNws/remotesa145c28f6b1/thebioengineer-tidytuesdayR-4d6d608/DESCRIPTION’ ...  ✓  checking for file ‘/private/var/folders/cg/0x9z12457xv1910wjyj19b1w0000gp/T/RtmpqOyNws/remotesa145c28f6b1/thebioengineer-tidytuesdayR-4d6d608/DESCRIPTION’
#>   ─  preparing ‘tidytuesdayR’:
#>      checking DESCRIPTION meta-information ...  ✓  checking DESCRIPTION meta-information
#>   ─  checking for LF line-endings in source and make files and shell scripts
#>   ─  checking for empty or unneeded directories
#>    Removed empty directory ‘tidytuesdayR/man/figures’
#>   ─  building ‘tidytuesdayR_1.0.1.9000.tar.gz’
#>      
#> 
library(tidytuesdayR)
fines_df <- tt_load("2020-04-21", local = locale(encoding = "latin1"))
#> --- Compiling #TidyTuesday Information for 2020-04-21 ----
#> --- There are 2 files available ---
#> --- Starting Download ---
#> 
#>  Downloading file 1 of 2: `gdpr_text.tsv`
#> Error in locale(encoding = "latin1"): could not find function "locale"
```

<sup>Created on 2020-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thebioengineer** [comment] 2020-07-24 00:30
Thanks for checking that out - the second example you gave is not an error from tidytuesdayR, but from you not having readr loaded into your namespace - could you try with just `tt_load("2020-04-21", local = "latin1")`? or `tt_load("2020-04-21", local = readr::locale(encoding = "latin1"))`

**Comment by chuckleong21** [comment] 2020-07-25 17:10
Hi, @thebioengineer . The issue is not with file encoding but with the **NA value** returned from `tt_data_type.csv` file in static folder inside TidyTuesday's repo. As you can see below:

```
> tt <- tt_load_gh("2020-04-21")
> str(tt)
 'tt' chr [1:2] "gdpr_text.tsv" "gdpr_violations.tsv"
 - attr(*, ".files")='data.frame':	2 obs. of  3 variables:
  ..$ data_files: chr [1:2] "gdpr_text.tsv" "gdpr_violations.tsv"
  ..$ data_type : chr [1:2] "tsv" "tsv"
  ..$ delim     : chr [1:2] NA NA
 - attr(*, ".readme")=List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr [1:2] "xml_document" "xml_node"
 - attr(*, ".date")= Date[1:1], format: "2020-04-21"
```

And in `tt_data_type.csv`:
|Week|Date|year|data_files|data_type|delim|
|---|---|---|---|---|---|
|17|2020-04-21|2020|gpdr_text.tsv|tsv|NA|

`read_delim()` does not recognize this for the delim argument, hence returns the multibyte string error. Here I presume @jthomasmock updates the file via automation every week. Then the updating program must have not properly handled .tsv files since the delim field for tsv files are NAs in the file.

The fastest fix for this issue would be complete the missing values. Otherwise, use "brute force" to try all the possible delimiters until read_delim() returns no error.

P.S. probably it's a viable idea for `read_delim()` to add an `delim = "auto"`, but at the cost of slowing down the process for there are more calculations.

**Comment by thebioengineer** [comment] 2020-07-25 21:59
Thanks for pointing that out, @chuckleong21 - I hadn't noticed that. @jthomasmock - I'll open a PR to fix those records ASAP. I'll also look into adding more "flexibility" to tidytuesdayR

**Closed** 2022-05-15 23:24 UTC
